### ISSUE TITLE
484: An ER doctor on how to triage your busy life | Darria Long | TEDxNaperville

### ISSUE THREAD

**Issue by shanuan** [littleflute/hz22#201]
https://www.youtube.com/watch?v=Fe1z22_Qd9E
https://mp.weixin.qq.com/s?__biz=MzIxOTc1MjU2NA==&mid=2247496514&idx=3&sn=709c2fa8be8346b814b8ac4a50a869d5&chksm=97d4c259a0a34b4f30112ee4c0078262d082e8a83ebc6b3ae7172718333acf615db369ed2079&scene=21#wechat_redirect

**Comment by littleflute** [comment]
hz22: https://mp.weixin.qq.com/s?__biz=MzI0MzU2MjMxNA==&mid=2247501701&idx=5&sn=b6151a43f664c470d29a15a42a352174&chksm=e969a5a0de1e2cb609a68f891c9b6e2c1fdaa4542f766c6bf27b95550b24afdb6644cc1e750d&token=2090833980&lang=zh_CN#rd

**Comment by littleflute** [comment]
https://www.youtube.com/watch?v=Fe1z22_Qd9E
