### ISSUE TITLE
485: The human skills we need in an unpredictable world | Margaret Heffernan

### ISSUE THREAD

**Issue by shanuan** [littleflute/hz22#202]
https://www.youtube.com/watch?v=w4OPtFCs_fw
https://mp.weixin.qq.com/s?__biz=MzIxOTc1MjU2NA==&mid=2247496590&idx=3&sn=86908cef7768e2f29535000a03b37c68&chksm=97d4c295a0a34b83bcfd17043ea29329d155e3ce15934ebdd60b884fd68322aa15c3db1d9409&scene=21#wechat_redirect

**Comment by littleflute** [comment]
https://www.youtube.com/watch?v=w4OPtFCs_fw

**Comment by littleflute** [comment]
hz22: 
https://mp.weixin.qq.com/s?__biz=MzI0MzU2MjMxNA==&mid=2247501692&idx=2&sn=3ceac7d9ca9c84e364499d5263923fac&chksm=e969a559de1e2c4f15850003feab520e52349835cd9af69ba6887690ab35cbf566d037d5828f&token=2090833980&lang=zh_CN#rd

**Comment by littleflute** [comment]
hz22: 
https://mp.weixin.qq.com/s?__biz=MzI0MzU2MjMxNA==&mid=2247501701&idx=6&sn=d31b2758b4e0b00d944eafd99fc60bd1&chksm=e969a5a0de1e2cb6143a5a40e57462aa00ff3741924a62daeb16ba8a55b75f6ea2ef68e37e92&token=2090833980&lang=zh_CN#rd
