### ISSUE TITLE
英文版《演员》 英文短视频 Yesterday

### ISSUE THREAD

**Issue by littleflute** [littleflute/hz22#243]
https://mp.weixin.qq.com/s/VrQhTAo3RA0nQVBJL3Q_vQ

**Comment by shanuan** [comment]
https://mp.weixin.qq.com/s/yvmawuwLXxI_f66ejTkEXQ

**Comment by shanuan** [comment]
https://mp.weixin.qq.com/s/w4_JSOgtPsiVaXFBvbu-5A

**Comment by shanuan** [comment]
https://mp.weixin.qq.com/s/ri7TWnysSMJRLjnzuN-UeA

**Comment by shanuan** [comment]
https://mp.weixin.qq.com/s/GTZSMEE1iyoxraGniBiM_g

**Comment by shanuan** [comment]
https://mp.weixin.qq.com/s/hHTokpPzaDeMO25feoBmiQ

**Comment by shanuan** [comment]
https://mp.weixin.qq.com/s/MKAe3cHwKJhP5_S7yhb1pw
